# apps.properties
apps=c-system,c-gateway,c-iot,c-tag,c-iot-gateway

c-system.local_path=./apps/c-system/app.jar
c-system.remote_url=http://192.168.1.115:9000/cicd-release/c-system/release-2-1-0/app.jar

c-gateway.local_path=./apps/c-gateway/app.jar
c-gateway.remote_url=http://192.168.1.115:9000/cicd-release/c-gateway/release-2-0-1/app.jar

c-iot.local_path=./apps/c-iot/app.jar
c-iot.remote_url=http://192.168.1.115:9000/cicd-release/c-iot-server/release-2-1-0/app.jar

c-tag.local_path=./apps/c-tag/app.jar
c-tag.remote_url=http://192.168.1.115:9000/cicd-release/c-tag/release-0-0-1/app.jar

c-iot-gateway.local_path=./apps/c-iot-gateway/app.jar
c-iot-gateway.remote_url=http://192.168.1.115:9000/cicd-release/c-iot-gateway/release-2-1-0/app.jar


