# apps.properties
apps=vmicro-app-system,vmicro-app-login,vmicro-app-main,vmicro-app-resource,vmicro-app-base-ctrl,static-resource

vmicro-app-system.local_path=./html/vmicro-app-system.zip
vmicro-app-system.remote_url=http://192.168.1.115:9000/cicd-release/html/vmicro-app-system/v2-1-0/vmicro-app-system.zip

vmicro-app-base-ctrl.local_path=./html/vmicro-app-base-ctrl.zip
vmicro-app-base-ctrl.remote_url=http://192.168.1.115:9000/cicd-release/html/vmicro-app-base-ctrl/v2-1-0/vmicro-app-base-ctrl.zip


vmicro-app-login.local_path=./html/vmicro-app-login.zip
vmicro-app-login.remote_url=http://192.168.1.115:9000/cicd-release/html/vmicro-app-login/v2-1-0/vmicro-app-login.zip

vmicro-app-main.local_path=./html/vmicro-app-main.zip
vmicro-app-main.remote_url=http://192.168.1.115:9000/cicd-release/html/vmicro-app-main/v2-1-0-b/vmicro-app-main.zip


vmicro-app-resource.local_path=./html/vmicro-app-resource.zip
vmicro-app-resource.remote_url=http://192.168.1.115:9000/cicd-release/html/vmicro-app-fly-config/v2-1-0/vmicro-app-resource.zip

static-resource.local_path=./html/static-resource.zip
static-resource.remote_url=http://192.168.1.115:9000/cicd-release/html/static-resource/v2-1-0/static-resource.zip


