# 容器监控
- targets: [ '192.168.1.104:9999' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'

# 服务器监控
- targets: [ '192.168.1.104:19100' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'

# 微服务基座监控
- targets: [ '192.168.1.104:48081' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'
    app: 'c-system'

- targets: [ '192.168.1.104:48080' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'
    app: 'c-gateway'

- targets: [ '192.168.1.104:48082' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'
    app: 'c-iot'

- targets: [ '192.168.1.104:48083' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'
    app: 'c-tag'

- targets: [ '192.168.1.104:48084' ]
  labels:
    env: 'dev2.1.0'
    host: '192.168.1.104'
    app: 'c-iot-gateway'
